config/routes.rb
InstaTech::Application.routes.draw do
  resources :users, :only => [:create, :new, :show]

  resources :feeds, :only => [:index, :create, :destroy] do
    resources :comments, :only => [:index, :create]
    resources :entries, :only => [:index, :destroy]
    resource :like, :only => [:create, :destroy]
    resources :tweets, :only => [:index, :create]
    resource :tweets, :only => [:destroy]
  end

  resources :entries, :only => [] do
    resources :comments, :only => [:index, :create]
    resource :like, :only => [:create, :destroy]
  end

  resource :session, :only => [:create, :destroy, :new]

  root :to => "StaticPages#root"
end

app/views/layouts/_add_news_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="add-news-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add RSS Feed Below:</h4>
      </div>
      <div class="modal-body">

				<form id="add_news_source" action="_add_news_modal_submit" method="post" accept-charset="utf-8" autocomplete="off">
					<input type="text" class="feed-url-input" name="feed[url]" placeholder="Input RSS URL..." id="feed_url" data-toggle="tooltip" data-placement="right" data-original-title="You didn't input anything!">

					<!-- <p><input type="submit" value="Continue &rarr;"></p> -->
				</form>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" data-loading-text="Saving..." class="btn btn-primary save-feed">Save</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/_footer.html.erb
<div id="footer">
	<div id="container">
		<!-- <p><a href="http://www.linkedin.com/in/davidattarzadeh">About Me</a>
			| <a href="mailto:dattar01@gmail.com">Contact</a> -->

	</div>
</div>

<!-- <div class="row">
	<div class="col-md-10">
		<ul class="list-unstyled">
			<li class="pull-right"><a href="http://www.linkedin.com/in/davidattarzadeh">About Me</a></li>
			<li class="pull-right"><a href="mailto:dattar01@gmail.com">Contact</a></li>
		</ul> -->

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">Amelia</a>
			</div>
				<div class="navbar-collapse collapse navbar-responsive-collapse">
					<ul class="nav navbar-nav">
						<li>
							<% if current_user.nil? %>
								<li><a href="/">Feeds</a>
							<% else %>
								<a href="/users/<%= current_user.id %>#/users/<%= current_user.id%>/feeds" class="feeds-link">Feeds</a>
							<% end %>
						</li>
						<li>
							<a href="#/feeds/allStories">All Stories</a>
						</li>
						<li class="trash-can">
							<a href="#"><img class="trash-can" src="/images/trash_can_inverted.png"></a>
						</li>
					</ul>

					<ul class="nav navbar-nav navbar-right">
						<% if current_user.nil? %>
							<li><%= link_to "Create Account", new_user_url %></li>
							<li><%= link_to "Sign in", new_session_url %></li>
						<% else %>
							<li>
								<a href="#" class="add-news-source" data-toggle="modal" data-target="#add-news-modal">Add News Source</a>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<%= current_user.username %><b class="caret"></b>
								</a>
								<ul class="dropdown-menu">
									<li>
										<a href="#">Profile</a>
									</li>
									<li>
										<%= link_to "Sign Out", session_url, method: :delete %>
									</li>
								</ul>
							</li>
						<% end %>
					</ul>
				</div>
		</div>
	</div>
</div>

<%= render 'layouts/add_news_modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstaTech</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

	<script type="text/javascript">
		$(document).ready(function() {
			$('body').toggleClass('on off');
		});
	</script>

</head>
<body class="off">
	<div id="wrap">
		<%= render 'layouts/header' %>
		<div class="backbone-container fadein scaleInv anim_1">

			<div class="inner-body fadein scaleInv anim_2">
				<%= yield %>
        <div id="feed-view"></div>
			</div>

			<div class= "body-footer fadein scaleInv anim_3">
				<%= render 'layouts/footer' %>
			</div>
		</div>
	</div>

</body>
</html>